### PR TITLE
pin torch to v2.0.1

### PR DESCRIPTION
**Pull request by 27am**
The image builds locally. Yet to test

### CODE REVIEW

**Comment by 27am** [comment]
Now that I think about it, wouldn't it be more clean to pin the pytorch version [here](https://github.com/SeaBee-no/seabee-ai/blob/master/docker/Dockerfile)?

**Comment by knl88** [comment]
Nja, guess this is more a environment problem, so if the software supports other versions I guess it is better to fix on install into the env that needs the fixed version:)

**Comment by knl88** [comment]
could also test if we can just use the pytorch cuda base image without the pinned version.

**Comment by JamesSample** [comment]
I think it's nice to have the same image on all the SeaBee Hubs, so users don't need to worry about packages, versions etc. when they switch. I already have PyTorch pinned in the main user env [here](https://github.com/SeaBee-no/dockerfiles/blob/main/hub-main/requirements_pip.txt) and the ML workflow is working nicely there (with seabeepy). I guess just pinning it to the same version here is a good solution.

**Comment by 27am** [comment]
> could also test if we can just use the pytorch cuda base image without the pinned version.

I would try only if the current approach doesn't work :)

**Comment by knl88** [comment]
Yep you can pin it here, but you need to add cuda to the runners docker image.

**Comment by knl88** [comment]
If you want to test it you can of course either just merge and wait or spin up a container on sigma2 with the gpu attached

**Comment by knl88** [comment]
It is also possible to change the base image to the hub image and use that:)

**Review by knl88 — APPROVED** [review]

**Pull request merged**
