### PR TITLE
Include NR ML package in seabeepy

### PR DESCRIPTION
**Pull request by 27am**
From issue https://github.com/SeaBee-no/seabeepy/issues/11

### CODE REVIEW

**Comment by knl88** [comment]
Have you checked that the needed system packages are installed also? so that the code can run

**Comment by 27am** [comment]
> Have you checked that the needed system packages are installed also? so that the code can run

The image builds correctly. When executed locally it fails because of a lack of permission on minIO

**Comment by knl88** [comment]
What entrypoint did you run? minio isn't too important but we need torch

```bash
kim@niva-osl-ans:~/work/seabee/seabeepy> docker run -it --entrypoint /bin/bash nr-detection
notebook@39f02584c2db:~$ nrseabee_det_test 
Traceback (most recent call last):
  File "/usr/local/bin/nrseabee_det_test", line 5, in <module>
    from nrseabee.det_05_test import cli
  File "/usr/local/lib/python3.10/dist-packages/nrseabee/det_05_test.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by knl88** [comment]
Perhaps we can just add torch in the dockerfile? the seabeepy python package that is using the requirements file doesn't need torch just now.  Think any cuda ubuntu image would do, but we can look at that later:)

**Pull request merged**
